-- ============================================================
-- INSERTAR CÓDIGOS POSTALES DE NUEVO LEÓN
-- ============================================================

-- Limpiar datos existentes
TRUNCATE TABLE codigos_postales CASCADE;

-- MONTERREY (Centro y colonias principales)
INSERT INTO codigos_postales (codigo, colonia, municipio, estado) VALUES
('64000', 'Centro', 'Monterrey', 'Nuevo León'),
('64010', 'Cuauhtémoc', 'Monterrey', 'Nuevo León'),
('64020', 'Independencia', 'Monterrey', 'Nuevo León'),
('64030', 'Reforma', 'Monterrey', 'Nuevo León'),
('64040', 'Barrio Antiguo', 'Monterrey', 'Nuevo León'),
('64050', 'Obispado', 'Monterrey', 'Nuevo León'),
('64060', 'Talleres', 'Monterrey', 'Nuevo León'),
('64070', 'Chepevera', 'Monterrey', 'Nuevo León'),
('64100', 'Del Valle', 'Monterrey', 'Nuevo León'),
('64102', 'Del Prado', 'Monterrey', 'Nuevo León'),
('64103', 'Residencial San Agustín', 'Monterrey', 'Nuevo León'),
('64104', 'Valle Soleado', 'Monterrey', 'Nuevo León'),
('64105', 'Valle del Mirador', 'Monterrey', 'Nuevo León'),
('64106', 'Contry', 'Monterrey', 'Nuevo León'),
('64107', 'Contry Sol', 'Monterrey', 'Nuevo León'),
('64108', 'Pedregal de la Silla', 'Monterrey', 'Nuevo León'),
('64109', 'Pedregal del Valle', 'Monterrey', 'Nuevo León'),
('64110', 'Lomas del Valle', 'Monterrey', 'Nuevo León'),
('64117', 'Cumbres 1er Sector', 'Monterrey', 'Nuevo León'),
('64118', 'Cumbres 2do Sector', 'Monterrey', 'Nuevo León'),
('64119', 'Cumbres 3er Sector', 'Monterrey', 'Nuevo León'),
('64120', 'Cumbres 4to Sector', 'Monterrey', 'Nuevo León'),
('64126', 'Cumbres Elite', 'Monterrey', 'Nuevo León'),
('64130', 'Valle de Chapultepec', 'Monterrey', 'Nuevo León'),
('64140', 'Colinas de San Jerónimo', 'Monterrey', 'Nuevo León'),
('64148', 'Cumbres Madeira', 'Monterrey', 'Nuevo León'),
('64149', 'Cumbres Provenza', 'Monterrey', 'Nuevo León'),
('64160', 'Residencial San Agustín', 'Monterrey', 'Nuevo León'),
('64170', 'Residencial Cumbres', 'Monterrey', 'Nuevo León'),
('64180', 'Valle de las Cumbres', 'Monterrey', 'Nuevo León'),
('64190', 'Contry Tesoro', 'Monterrey', 'Nuevo León'),
('64200', 'Félix U. Gómez', 'Monterrey', 'Nuevo León'),
('64210', 'Vista Hermosa', 'Monterrey', 'Nuevo León'),
('64220', 'Bernardo Reyes', 'Monterrey', 'Nuevo León'),
('64230', 'Mitras Norte', 'Monterrey', 'Nuevo León'),
('64238', 'Mitras Norte 2do Sector', 'Monterrey', 'Nuevo León'),
('64240', 'Mitras Centro', 'Monterrey', 'Nuevo León'),
('64250', 'Mitras Sur', 'Monterrey', 'Nuevo León'),
('64260', 'Lomas de San Francisco', 'Monterrey', 'Nuevo León'),
('64270', 'Lomas del Rosario', 'Monterrey', 'Nuevo León'),
('64280', 'Las Puentes', 'Monterrey', 'Nuevo León'),
('64290', 'Lomas de Anáhuac', 'Monterrey', 'Nuevo León'),
('64300', 'Terminal', 'Monterrey', 'Nuevo León'),
('64310', 'Estanzuela', 'Monterrey', 'Nuevo León'),
('64320', 'Buenos Aires', 'Monterrey', 'Nuevo León'),
('64330', 'Anahuac', 'Monterrey', 'Nuevo León'),
('64340', 'Constituyentes del 57', 'Monterrey', 'Nuevo León'),
('64350', 'Treviño', 'Monterrey', 'Nuevo León'),
('64360', 'Residencial Aztlán', 'Monterrey', 'Nuevo León'),
('64370', 'Las Puentes 1er Sector', 'Monterrey', 'Nuevo León'),
('64380', 'Las Puentes 2do Sector', 'Monterrey', 'Nuevo León'),
('64390', 'Las Puentes 3er Sector', 'Monterrey', 'Nuevo León'),
('64400', 'Plutarco Elías Calles', 'Monterrey', 'Nuevo León'),
('64410', 'República Mexicana', 'Monterrey', 'Nuevo León'),
('64420', 'Industrial', 'Monterrey', 'Nuevo León'),
('64430', 'Moderna', 'Monterrey', 'Nuevo León'),
('64440', 'Tecnológico', 'Monterrey', 'Nuevo León'),
('64450', 'Colinas del Tecnológico', 'Monterrey', 'Nuevo León'),
('64460', 'Residencial Tecnológico', 'Monterrey', 'Nuevo León'),
('64470', 'Joyas del Campestre', 'Monterrey', 'Nuevo León'),
('64480', 'Jardín Español', 'Monterrey', 'Nuevo León'),
('64490', 'Mirasol', 'Monterrey', 'Nuevo León'),
('64500', 'Fuentes del Valle', 'Monterrey', 'Nuevo León'),
('64510', 'Canteras', 'Monterrey', 'Nuevo León'),
('64520', 'Obrera', 'Monterrey', 'Nuevo León'),
('64530', 'Alfonso Reyes', 'Monterrey', 'Nuevo León'),
('64540', 'San Nicolás de los Garza', 'Monterrey', 'Nuevo León'),
('64550', 'Cuauhtémoc', 'Monterrey', 'Nuevo León'),
('64560', 'Fierro', 'Monterrey', 'Nuevo León'),
('64570', 'Bellavista', 'Monterrey', 'Nuevo León'),
('64580', 'Bella Vista', 'Monterrey', 'Nuevo León'),
('64590', 'Lázaro Cárdenas', 'Monterrey', 'Nuevo León'),
('64600', 'Jardines de la Silla', 'Monterrey', 'Nuevo León'),
('64610', 'Croc', 'Monterrey', 'Nuevo León'),
('64620', 'CampestreVirreyes', 'Monterrey', 'Nuevo León'),
('64630', 'Hacienda los Morales', 'Monterrey', 'Nuevo León'),
('64639', 'Residencial Santa Bárbara', 'Monterrey', 'Nuevo León'),
('64640', 'Residencial Chipinque', 'Monterrey', 'Nuevo León'),
('64650', 'San Jerónimo', 'Monterrey', 'Nuevo León'),
('64660', 'Colinas de San Jerónimo', 'Monterrey', 'Nuevo León'),
('64700', 'Santa María', 'Monterrey', 'Nuevo León'),
('64710', 'Balcones de Anáhuac', 'Monterrey', 'Nuevo León'),
('64720', 'Balcones de Santo Domingo', 'Monterrey', 'Nuevo León'),
('64730', 'Privada la Estancia', 'Monterrey', 'Nuevo León'),
('64740', 'San Francisco', 'Monterrey', 'Nuevo León'),
('64750', 'Pedregal Cumbres', 'Monterrey', 'Nuevo León'),
('64760', 'Valle Alto', 'Monterrey', 'Nuevo León'),
('64770', 'Colinas del Valle', 'Monterrey', 'Nuevo León'),
('64780', 'Residencial Cordillera', 'Monterrey', 'Nuevo León'),
('64790', 'Residencial Cumbres', 'Monterrey', 'Nuevo León'),
('64800', 'Rincón de la Sierra', 'Monterrey', 'Nuevo León'),
('64810', 'Hacienda los Morales', 'Monterrey', 'Nuevo León'),
('64820', 'Hacienda San Pedro', 'Monterrey', 'Nuevo León'),
('64830', 'Las Puentes Sector 4', 'Monterrey', 'Nuevo León'),
('64840', 'Las Puentes Sector 5', 'Monterrey', 'Nuevo León'),
('64849', 'Las Puentes Sector 6', 'Monterrey', 'Nuevo León'),
('64850', 'Las Puentes Sector 7', 'Monterrey', 'Nuevo León'),
('64860', 'Las Puentes Sector 8', 'Monterrey', 'Nuevo León'),
('64868', 'Las Puentes Sector 9', 'Monterrey', 'Nuevo León'),
('64870', 'Las Puentes Sector 10', 'Monterrey', 'Nuevo León'),
('64880', 'Las Puentes Sector 11', 'Monterrey', 'Nuevo León'),
('64890', 'Las Puentes Sector 12', 'Monterrey', 'Nuevo León'),
('64900', 'Parque Industrial Santa Catarina', 'Monterrey', 'Nuevo León'),
('64910', 'Parque Industrial Nexxus', 'Monterrey', 'Nuevo León'),
('64920', 'Alameda', 'Monterrey', 'Nuevo León'),
('64930', 'Riveras del Paseo', 'Monterrey', 'Nuevo León'),
('64940', 'Nueva Estanzuela', 'Monterrey', 'Nuevo León'),
('64950', 'Los Morales', 'Monterrey', 'Nuevo León'),
('64960', 'San Ángel', 'Monterrey', 'Nuevo León'),
('64970', 'San Agustín', 'Monterrey', 'Nuevo León'),
('64980', 'Valle de Infonavit', 'Monterrey', 'Nuevo León'),
('64988', 'Valle del Vergel', 'Monterrey', 'Nuevo León'),
('64990', 'Los Girasoles', 'Monterrey', 'Nuevo León');

-- SAN NICOLÁS DE LOS GARZA
INSERT INTO codigos_postales (codigo, colonia, municipio, estado) VALUES
('66000', 'Centro', 'San Nicolás de los Garza', 'Nuevo León'),
('66010', 'Anáhuac', 'San Nicolás de los Garza', 'Nuevo León'),
('66020', 'Cuauhtémoc', 'San Nicolás de los Garza', 'Nuevo León'),
('66030', 'Benito Juárez', 'San Nicolás de los Garza', 'Nuevo León'),
('66040', 'Miguel Alemán', 'San Nicolás de los Garza', 'Nuevo León'),
('66050', 'Niños Héroes', 'San Nicolás de los Garza', 'Nuevo León'),
('66060', 'Altavista', 'San Nicolás de los Garza', 'Nuevo León'),
('66070', 'Residencial Palo Blanco', 'San Nicolás de los Garza', 'Nuevo León'),
('66100', 'Del Norte', 'San Nicolás de los Garza', 'Nuevo León'),
('66103', 'Valle de Linda Vista', 'San Nicolás de los Garza', 'Nuevo León'),
('66104', 'Linda Vista', 'San Nicolás de los Garza', 'Nuevo León'),
('66105', 'Las Puentes 6to Sector', 'San Nicolás de los Garza', 'Nuevo León'),
('66110', 'El Refugio', 'San Nicolás de los Garza', 'Nuevo León'),
('66113', 'Balcones de Anáhuac', 'San Nicolás de los Garza', 'Nuevo León'),
('66114', 'Residencial Anáhuac', 'San Nicolás de los Garza', 'Nuevo León'),
('66115', 'Las Puentes 1er Sector', 'San Nicolás de los Garza', 'Nuevo León'),
('66116', 'Las Puentes 2do Sector', 'San Nicolás de los Garza', 'Nuevo León'),
('66117', 'Las Puentes 3er Sector', 'San Nicolás de los Garza', 'Nuevo León'),
('66118', 'Las Puentes 4to Sector', 'San Nicolás de los Garza', 'Nuevo León'),
('66119', 'Las Puentes 5to Sector', 'San Nicolás de los Garza', 'Nuevo León'),
('66120', 'Valle Soleado', 'San Nicolás de los Garza', 'Nuevo León'),
('66130', 'Residencial Anáhuac Sector 1', 'San Nicolás de los Garza', 'Nuevo León'),
('66140', 'Residencial Anáhuac Sector 2', 'San Nicolás de los Garza', 'Nuevo León'),
('66150', 'Residencial Anáhuac Sector 3', 'San Nicolás de los Garza', 'Nuevo León'),
('66170', 'Privadas de Anáhuac', 'San Nicolás de los Garza', 'Nuevo León'),
('66180', 'Privadas de Anáhuac Sector 2', 'San Nicolás de los Garza', 'Nuevo León'),
('66190', 'Privadas de Anáhuac Sector 3', 'San Nicolás de los Garza', 'Nuevo León'),
('66196', 'Privadas de Anáhuac Sector 4', 'San Nicolás de los Garza', 'Nuevo León'),
('66197', 'Privadas de Anáhuac Sector 5', 'San Nicolás de los Garza', 'Nuevo León'),
('66198', 'Privadas de Anáhuac Sector 6', 'San Nicolás de los Garza', 'Nuevo León'),
('66200', 'Hacienda los Morales', 'San Nicolás de los Garza', 'Nuevo León'),
('66210', 'Las Brisas', 'San Nicolás de los Garza', 'Nuevo León'),
('66220', 'Rincón de la Primavera', 'San Nicolás de los Garza', 'Nuevo León'),
('66230', 'Rincón de las Colinas', 'San Nicolás de los Garza', 'Nuevo León'),
('66240', 'Rincón de Anáhuac', 'San Nicolás de los Garza', 'Nuevo León'),
('66250', 'Cumbres Anáhuac', 'San Nicolás de los Garza', 'Nuevo León'),
('66260', 'Cumbres Universidad', 'San Nicolás de los Garza', 'Nuevo León'),
('66267', 'Cumbres de Anáhuac', 'San Nicolás de los Garza', 'Nuevo León'),
('66268', 'Cumbres de la Silla', 'San Nicolás de los Garza', 'Nuevo León'),
('66269', 'Cumbres Platino', 'San Nicolás de los Garza', 'Nuevo León'),
('66270', 'Privadas Cumbres', 'San Nicolás de los Garza', 'Nuevo León'),
('66280', 'Jardines de Anáhuac', 'San Nicolás de los Garza', 'Nuevo León'),
('66300', 'San Nicolás', 'San Nicolás de los Garza', 'Nuevo León'),
('66310', 'Santa María', 'San Nicolás de los Garza', 'Nuevo León'),
('66320', 'Colinas de San Jerónimo', 'San Nicolás de los Garza', 'Nuevo León'),
('66330', 'Residencial San Jerónimo', 'San Nicolás de los Garza', 'Nuevo León'),
('66340', 'Estanzuela Nueva', 'San Nicolás de los Garza', 'Nuevo León'),
('66350', 'Balcones de Santo Domingo', 'San Nicolás de los Garza', 'Nuevo León'),
('66360', 'Las Colinas', 'San Nicolás de los Garza', 'Nuevo León'),
('66367', 'Las Villas', 'San Nicolás de los Garza', 'Nuevo León'),
('66368', 'Rincón de los Sabinos', 'San Nicolás de los Garza', 'Nuevo León'),
('66369', 'Valle de San Ángel', 'San Nicolás de los Garza', 'Nuevo León'),
('66370', 'Las Torres', 'San Nicolás de los Garza', 'Nuevo León'),
('66380', 'La Playa', 'San Nicolás de los Garza', 'Nuevo León'),
('66390', 'Residencial Escobedo', 'San Nicolás de los Garza', 'Nuevo León'),
('66400', 'Unidad Modelo', 'San Nicolás de los Garza', 'Nuevo León'),
('66410', 'Valle del Roble', 'San Nicolás de los Garza', 'Nuevo León'),
('66412', 'Pedregal de Anáhuac', 'San Nicolás de los Garza', 'Nuevo León'),
('66413', 'Pedregal del Valle', 'San Nicolás de los Garza', 'Nuevo León'),
('66414', 'Pedregal de la Silla', 'San Nicolás de los Garza', 'Nuevo León'),
('66415', 'Lomas de Anáhuac', 'San Nicolás de los Garza', 'Nuevo León'),
('66420', 'Jardines de la Silla', 'San Nicolás de los Garza', 'Nuevo León'),
('66430', 'Jardines de San Nicolás', 'San Nicolás de los Garza', 'Nuevo León'),
('66440', 'Colonia del Norte', 'San Nicolás de los Garza', 'Nuevo León'),
('66450', 'Alfareros', 'San Nicolás de los Garza', 'Nuevo León'),
('66455', 'Artesanos', 'San Nicolás de los Garza', 'Nuevo León'),
('66460', 'Fomerrey 35', 'San Nicolás de los Garza', 'Nuevo León'),
('66470', 'Santo Domingo', 'San Nicolás de los Garza', 'Nuevo León'),
('66477', 'Burócratas del Estado', 'San Nicolás de los Garza', 'Nuevo León'),
('66478', 'Chapultepec Norte', 'San Nicolás de los Garza', 'Nuevo León'),
('66480', 'Moderna', 'San Nicolás de los Garza', 'Nuevo León'),
('66490', 'Valle de Chapultepec', 'San Nicolás de los Garza', 'Nuevo León'),
('66495', 'Valle de San Miguel', 'San Nicolás de los Garza', 'Nuevo León'),
('66496', 'Valle Verde 1er Sector', 'San Nicolás de los Garza', 'Nuevo León'),
('66497', 'Valle Verde 2do Sector', 'San Nicolás de los Garza', 'Nuevo León'),
('66498', 'Valle Verde 3er Sector', 'San Nicolás de los Garza', 'Nuevo León'),
('66499', 'Valle Verde 4to Sector', 'San Nicolás de los Garza', 'Nuevo León');

-- GUADALUPE
INSERT INTO codigos_postales (codigo, colonia, municipio, estado) VALUES
('67100', 'Centro', 'Guadalupe', 'Nuevo León'),
('67110', 'La Purísima', 'Guadalupe', 'Nuevo León'),
('67113', 'Las Quintas', 'Guadalupe', 'Nuevo León'),
('67114', 'Guadalupe', 'Guadalupe', 'Nuevo León'),
('67115', 'Paseo de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67116', 'Balcones de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67117', 'Rincón de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67118', 'Valle de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67119', 'Privadas de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67120', 'Del Paseo Residencial', 'Guadalupe', 'Nuevo León'),
('67125', 'Colonial del Valle', 'Guadalupe', 'Nuevo León'),
('67126', 'Valle de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67127', 'Contry Sur', 'Guadalupe', 'Nuevo León'),
('67128', 'Prados de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67129', 'Jardines de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67130', 'Jardines de la Silla', 'Guadalupe', 'Nuevo León'),
('67134', 'Los Encinos', 'Guadalupe', 'Nuevo León'),
('67135', 'Los Nogales', 'Guadalupe', 'Nuevo León'),
('67136', 'Privadas del Valle', 'Guadalupe', 'Nuevo León'),
('67137', 'Residencial del Valle', 'Guadalupe', 'Nuevo León'),
('67138', 'Valle de las Flores', 'Guadalupe', 'Nuevo León'),
('67139', 'Villas de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67140', 'Las Huertas', 'Guadalupe', 'Nuevo León'),
('67143', 'Privadas de las Huertas', 'Guadalupe', 'Nuevo León'),
('67144', 'Rincón de las Huertas', 'Guadalupe', 'Nuevo León'),
('67145', 'Valle de las Huertas', 'Guadalupe', 'Nuevo León'),
('67146', 'Praderas de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67147', 'Joyas de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67148', 'Portales de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67149', 'Valles de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67150', 'Misión de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67154', 'Hacienda de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67155', 'Las Palmas', 'Guadalupe', 'Nuevo León'),
('67156', 'Privadas de la Hacienda', 'Guadalupe', 'Nuevo León'),
('67157', 'Rinconada de la Hacienda', 'Guadalupe', 'Nuevo León'),
('67158', 'Valle de la Hacienda', 'Guadalupe', 'Nuevo León'),
('67159', 'Villa de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67160', 'Paseo de las Mitras', 'Guadalupe', 'Nuevo León'),
('67163', 'Privadas de las Mitras', 'Guadalupe', 'Nuevo León'),
('67164', 'Rincón de las Mitras', 'Guadalupe', 'Nuevo León'),
('67165', 'Valle de las Mitras', 'Guadalupe', 'Nuevo León'),
('67166', 'Colinas de las Mitras', 'Guadalupe', 'Nuevo León'),
('67167', 'Lomas de las Mitras', 'Guadalupe', 'Nuevo León'),
('67168', 'Residencial las Mitras', 'Guadalupe', 'Nuevo León'),
('67169', 'Villas de las Mitras', 'Guadalupe', 'Nuevo León'),
('67170', 'Valle Soleado', 'Guadalupe', 'Nuevo León'),
('67173', 'Privadas del Sol', 'Guadalupe', 'Nuevo León'),
('67174', 'Rincón del Sol', 'Guadalupe', 'Nuevo León'),
('67175', 'Villa del Sol', 'Guadalupe', 'Nuevo León'),
('67176', 'Bosques del Valle', 'Guadalupe', 'Nuevo León'),
('67177', 'Jardines del Valle', 'Guadalupe', 'Nuevo León'),
('67178', 'Prados del Valle', 'Guadalupe', 'Nuevo León'),
('67179', 'Villas del Valle', 'Guadalupe', 'Nuevo León'),
('67180', 'Paseo de Cumbres', 'Guadalupe', 'Nuevo León'),
('67183', 'Privadas de Cumbres', 'Guadalupe', 'Nuevo León'),
('67184', 'Rincón de Cumbres', 'Guadalupe', 'Nuevo León'),
('67185', 'Valle de Cumbres', 'Guadalupe', 'Nuevo León'),
('67186', 'Colinas de Cumbres', 'Guadalupe', 'Nuevo León'),
('67187', 'Lomas de Cumbres', 'Guadalupe', 'Nuevo León'),
('67188', 'Residencial Cumbres', 'Guadalupe', 'Nuevo León'),
('67189', 'Villas de Cumbres', 'Guadalupe', 'Nuevo León'),
('67190', 'Valle del Campestre', 'Guadalupe', 'Nuevo León'),
('67193', 'Privadas del Campestre', 'Guadalupe', 'Nuevo León'),
('67194', 'Rincón del Campestre', 'Guadalupe', 'Nuevo León'),
('67195', 'Villa Campestre', 'Guadalupe', 'Nuevo León'),
('67196', 'Bosques del Campestre', 'Guadalupe', 'Nuevo León'),
('67197', 'Jardines del Campestre', 'Guadalupe', 'Nuevo León'),
('67198', 'Prados del Campestre', 'Guadalupe', 'Nuevo León'),
('67199', 'Villas del Campestre', 'Guadalupe', 'Nuevo León');

-- APODACA
INSERT INTO codigos_postales (codigo, colonia, municipio, estado) VALUES
('66600', 'Centro', 'Apodaca', 'Nuevo León'),
('66601', 'Pueblo Nuevo', 'Apodaca', 'Nuevo León'),
('66602', 'Puerta de Hierro', 'Apodaca', 'Nuevo León'),
('66603', 'Real de Palmas', 'Apodaca', 'Nuevo León'),
('66604', 'Rinconada de Apodaca', 'Apodaca', 'Nuevo León'),
('66605', 'Valle de Apodaca', 'Apodaca', 'Nuevo León'),
('66606', 'Villa de Apodaca', 'Apodaca', 'Nuevo León'),
('66607', 'Privadas de Apodaca', 'Apodaca', 'Nuevo León'),
('66608', 'Jardines de Apodaca', 'Apodaca', 'Nuevo León'),
('66609', 'Hacienda de Apodaca', 'Apodaca', 'Nuevo León'),
('66610', 'Las Américas', 'Apodaca', 'Nuevo León'),
('66612', 'Privadas las Américas', 'Apodaca', 'Nuevo León'),
('66613', 'Valle de las Américas', 'Apodaca', 'Nuevo León'),
('66614', 'Villa de las Américas', 'Apodaca', 'Nuevo León'),
('66615', 'Jardines de las Américas', 'Apodaca', 'Nuevo León'),
('66616', 'Praderas de las Américas', 'Apodaca', 'Nuevo León'),
('66617', 'Rincón de las Américas', 'Apodaca', 'Nuevo León'),
('66618', 'Bosques de las Américas', 'Apodaca', 'Nuevo León'),
('66619', 'Colinas de las Américas', 'Apodaca', 'Nuevo León'),
('66620', 'Pueblo Nuevo II', 'Apodaca', 'Nuevo León'),
('66622', 'Privadas Pueblo Nuevo', 'Apodaca', 'Nuevo León'),
('66623', 'Valle Pueblo Nuevo', 'Apodaca', 'Nuevo León'),
('66624', 'Villa Pueblo Nuevo', 'Apodaca', 'Nuevo León'),
('66625', 'Jardines Pueblo Nuevo', 'Apodaca', 'Nuevo León'),
('66626', 'Praderas Pueblo Nuevo', 'Apodaca', 'Nuevo León'),
('66627', 'Rincón Pueblo Nuevo', 'Apodaca', 'Nuevo León'),
('66628', 'Bosques Pueblo Nuevo', 'Apodaca', 'Nuevo León'),
('66629', 'Colinas Pueblo Nuevo', 'Apodaca', 'Nuevo León'),
('66630', 'Privadas de las Palmas', 'Apodaca', 'Nuevo León'),
('66633', 'Valle de las Palmas', 'Apodaca', 'Nuevo León'),
('66634', 'Villa de las Palmas', 'Apodaca', 'Nuevo León'),
('66635', 'Jardines de las Palmas', 'Apodaca', 'Nuevo León'),
('66636', 'Praderas de las Palmas', 'Apodaca', 'Nuevo León'),
('66637', 'Rincón de las Palmas', 'Apodaca', 'Nuevo León'),
('66638', 'Bosques de las Palmas', 'Apodaca', 'Nuevo León'),
('66639', 'Colinas de las Palmas', 'Apodaca', 'Nuevo León'),
('66640', 'Parque Industrial Apodaca', 'Apodaca', 'Nuevo León'),
('66645', 'Parque Industrial Milenium', 'Apodaca', 'Nuevo León'),
('66646', 'Parque Industrial Nexxus', 'Apodaca', 'Nuevo León'),
('66647', 'Parque Industrial Kalos', 'Apodaca', 'Nuevo León'),
('66648', 'Parque Industrial Finsa', 'Apodaca', 'Nuevo León'),
('66649', 'Parque Industrial Interpuerto', 'Apodaca', 'Nuevo León'),
('66650', 'Privadas del Parque', 'Apodaca', 'Nuevo León'),
('66653', 'Valle del Parque', 'Apodaca', 'Nuevo León'),
('66654', 'Villa del Parque', 'Apodaca', 'Nuevo León'),
('66655', 'Jardines del Parque', 'Apodaca', 'Nuevo León'),
('66656', 'Praderas del Parque', 'Apodaca', 'Nuevo León'),
('66657', 'Rincón del Parque', 'Apodaca', 'Nuevo León'),
('66658', 'Bosques del Parque', 'Apodaca', 'Nuevo León'),
('66659', 'Colinas del Parque', 'Apodaca', 'Nuevo León');

-- SANTA CATARINA
INSERT INTO codigos_postales (codigo, colonia, municipio, estado) VALUES
('66100', 'Centro', 'Santa Catarina', 'Nuevo León'),
('66104', 'Valle Soleado', 'Santa Catarina', 'Nuevo León'),
('66105', 'Privadas del Valle', 'Santa Catarina', 'Nuevo León'),
('66106', 'Villa del Valle', 'Santa Catarina', 'Nuevo León'),
('66107', 'Jardines del Valle', 'Santa Catarina', 'Nuevo León'),
('66108', 'Praderas del Valle', 'Santa Catarina', 'Nuevo León'),
('66109', 'Rincón del Valle', 'Santa Catarina', 'Nuevo León'),
('66110', 'Bosques de Satélite', 'Santa Catarina', 'Nuevo León'),
('66113', 'Privadas Satélite', 'Santa Catarina', 'Nuevo León'),
('66114', 'Valle Satélite', 'Santa Catarina', 'Nuevo León'),
('66115', 'Villa Satélite', 'Santa Catarina', 'Nuevo León'),
('66116', 'Jardines Satélite', 'Santa Catarina', 'Nuevo León'),
('66117', 'Praderas Satélite', 'Santa Catarina', 'Nuevo León'),
('66118', 'Rincón Satélite', 'Santa Catarina', 'Nuevo León'),
('66119', 'Colinas Satélite', 'Santa Catarina', 'Nuevo León'),
('66120', 'Fomerrey 1', 'Santa Catarina', 'Nuevo León'),
('66123', 'Fomerrey 2', 'Santa Catarina', 'Nuevo León'),
('66124', 'Fomerrey 3', 'Santa Catarina', 'Nuevo León'),
('66125', 'Fomerrey 4', 'Santa Catarina', 'Nuevo León'),
('66126', 'Fomerrey 5', 'Santa Catarina', 'Nuevo León'),
('66127', 'Fomerrey 6', 'Santa Catarina', 'Nuevo León'),
('66128', 'Fomerrey 7', 'Santa Catarina', 'Nuevo León'),
('66129', 'Fomerrey 8', 'Santa Catarina', 'Nuevo León'),
('66130', 'Valle de Santa Catarina', 'Santa Catarina', 'Nuevo León'),
('66133', 'Privadas de Santa Catarina', 'Santa Catarina', 'Nuevo León'),
('66134', 'Villa de Santa Catarina', 'Santa Catarina', 'Nuevo León'),
('66135', 'Jardines de Santa Catarina', 'Santa Catarina', 'Nuevo León'),
('66136', 'Praderas de Santa Catarina', 'Santa Catarina', 'Nuevo León'),
('66137', 'Rincón de Santa Catarina', 'Santa Catarina', 'Nuevo León'),
('66138', 'Bosques de Santa Catarina', 'Santa Catarina', 'Nuevo León'),
('66139', 'Colinas de Santa Catarina', 'Santa Catarina', 'Nuevo León'),
('66140', 'Hacienda de Santa Catarina', 'Santa Catarina', 'Nuevo León'),
('66143', 'Privadas de la Hacienda', 'Santa Catarina', 'Nuevo León'),
('66144', 'Valle de la Hacienda', 'Santa Catarina', 'Nuevo León'),
('66145', 'Villa de la Hacienda', 'Santa Catarina', 'Nuevo León'),
('66146', 'Jardines de la Hacienda', 'Santa Catarina', 'Nuevo León'),
('66147', 'Praderas de la Hacienda', 'Santa Catarina', 'Nuevo León'),
('66148', 'Rincón de la Hacienda', 'Santa Catarina', 'Nuevo León'),
('66149', 'Bosques de la Hacienda', 'Santa Catarina', 'Nuevo León'),
('66150', 'Parque Industrial Santa Catarina', 'Santa Catarina', 'Nuevo León'),
('66155', 'Parque Industrial Finsa', 'Santa Catarina', 'Nuevo León'),
('66156', 'Parque Industrial Kalos', 'Santa Catarina', 'Nuevo León'),
('66157', 'Parque Industrial Nexxus', 'Santa Catarina', 'Nuevo León'),
('66158', 'Parque Industrial Milenium', 'Santa Catarina', 'Nuevo León'),
('66159', 'Parque Industrial Interpuerto', 'Santa Catarina', 'Nuevo León');

-- ESCOBEDO
INSERT INTO codigos_postales (codigo, colonia, municipio, estado) VALUES
('66050', 'Centro', 'Escobedo', 'Nuevo León'),
('66052', 'Raúl Caballero', 'Escobedo', 'Nuevo León'),
('66053', 'Alianza Real', 'Escobedo', 'Nuevo León'),
('66054', 'Balcones de Escobedo', 'Escobedo', 'Nuevo León'),
('66055', 'Valle de Escobedo', 'Escobedo', 'Nuevo León'),
('66056', 'Villa de Escobedo', 'Escobedo', 'Nuevo León'),
('66057', 'Privadas de Escobedo', 'Escobedo', 'Nuevo León'),
('66058', 'Jardines de Escobedo', 'Escobedo', 'Nuevo León'),
('66059', 'Hacienda de Escobedo', 'Escobedo', 'Nuevo León'),
('66060', 'Privadas del Norte', 'Escobedo', 'Nuevo León'),
('66062', 'Valle del Norte', 'Escobedo', 'Nuevo León'),
('66063', 'Villa del Norte', 'Escobedo', 'Nuevo León'),
('66064', 'Jardines del Norte', 'Escobedo', 'Nuevo León'),
('66065', 'Praderas del Norte', 'Escobedo', 'Nuevo León'),
('66066', 'Rincón del Norte', 'Escobedo', 'Nuevo León'),
('66067', 'Bosques del Norte', 'Escobedo', 'Nuevo León'),
('66068', 'Colinas del Norte', 'Escobedo', 'Nuevo León'),
('66069', 'Hacienda del Norte', 'Escobedo', 'Nuevo León'),
('66070', 'Paseo de las Lomas', 'Escobedo', 'Nuevo León'),
('66072', 'Privadas de las Lomas', 'Escobedo', 'Nuevo León'),
('66073', 'Valle de las Lomas', 'Escobedo', 'Nuevo León'),
('66074', 'Villa de las Lomas', 'Escobedo', 'Nuevo León'),
('66075', 'Jardines de las Lomas', 'Escobedo', 'Nuevo León'),
('66076', 'Praderas de las Lomas', 'Escobedo', 'Nuevo León'),
('66077', 'Rincón de las Lomas', 'Escobedo', 'Nuevo León'),
('66078', 'Bosques de las Lomas', 'Escobedo', 'Nuevo León'),
('66079', 'Colinas de las Lomas', 'Escobedo', 'Nuevo León'),
('66080', 'Parque Industrial Escobedo', 'Escobedo', 'Nuevo León'),
('66085', 'Parque Industrial Milenium', 'Escobedo', 'Nuevo León'),
('66086', 'Parque Industrial Nexxus', 'Escobedo', 'Nuevo León'),
('66087', 'Parque Industrial Kalos', 'Escobedo', 'Nuevo León'),
('66088', 'Parque Industrial Finsa', 'Escobedo', 'Nuevo León'),
('66089', 'Parque Industrial Interpuerto', 'Escobedo', 'Nuevo León');

-- SAN PEDRO GARZA GARCÍA
INSERT INTO codigos_postales (codigo, colonia, municipio, estado) VALUES
('66200', 'Centro', 'San Pedro Garza García', 'Nuevo León'),
('66210', 'Del Valle', 'San Pedro Garza García', 'Nuevo León'),
('66220', 'Fuentes del Valle', 'San Pedro Garza García', 'Nuevo León'),
('66230', 'Colinas del Valle', 'San Pedro Garza García', 'Nuevo León'),
('66240', 'Residencial San Agustín', 'San Pedro Garza García', 'Nuevo León'),
('66250', 'Residencial Santa Bárbara', 'San Pedro Garza García', 'Nuevo León'),
('66260', 'Residencial Chipinque', 'San Pedro Garza García', 'Nuevo León'),
('66265', 'Residencial Cordillera', 'San Pedro Garza García', 'Nuevo León'),
('66266', 'Residencial Cumbres', 'San Pedro Garza García', 'Nuevo León'),
('67110', 'Del Valle', 'San Pedro Garza García', 'Nuevo León'),
('67120', 'Fuentes del Valle', 'San Pedro Garza García', 'Nuevo León'),
('67124', 'Privadas del Valle', 'San Pedro Garza García', 'Nuevo León'),
('67125', 'Valle Campestre', 'San Pedro Garza García', 'Nuevo León'),
('67126', 'Valle Oriente', 'San Pedro Garza García', 'Nuevo León'),
('67127', 'Valle Poniente', 'San Pedro Garza García', 'Nuevo León'),
('67128', 'Valle Norte', 'San Pedro Garza García', 'Nuevo León'),
('67129', 'Valle Sur', 'San Pedro Garza García', 'Nuevo León'),
('67130', 'Residencial San Agustín', 'San Pedro Garza García', 'Nuevo León'),
('67135', 'Residencial Santa Bárbara', 'San Pedro Garza García', 'Nuevo León'),
('67136', 'Residencial Chipinque', 'San Pedro Garza García', 'Nuevo León'),
('67137', 'Residencial Cordillera', 'San Pedro Garza García', 'Nuevo León'),
('67138', 'Residencial Cumbres', 'San Pedro Garza García', 'Nuevo León'),
('67139', 'Residencial La Silla', 'San Pedro Garza García', 'Nuevo León'),
('67140', 'Colinas de San Jerónimo', 'San Pedro Garza García', 'Nuevo León'),
('67143', 'Privadas de San Jerónimo', 'San Pedro Garza García', 'Nuevo León'),
('67144', 'Valle de San Jerónimo', 'San Pedro Garza García', 'Nuevo León'),
('67145', 'Residencial San Jerónimo', 'San Pedro Garza García', 'Nuevo León'),
('67146', 'Jardines de San Jerónimo', 'San Pedro Garza García', 'Nuevo León'),
('67147', 'Praderas de San Jerónimo', 'San Pedro Garza García', 'Nuevo León'),
('67148', 'Rincón de San Jerónimo', 'San Pedro Garza García', 'Nuevo León'),
('67149', 'Bosques de San Jerónimo', 'San Pedro Garza García', 'Nuevo León'),
('67150', 'Calzada del Valle', 'San Pedro Garza García', 'Nuevo León'),
('67153', 'Privadas del Valle', 'San Pedro Garza García', 'Nuevo León'),
('67154', 'Rincón del Valle', 'San Pedro Garza García', 'Nuevo León'),
('67155', 'Villa del Valle', 'San Pedro Garza García', 'Nuevo León'),
('67156', 'Jardines del Valle', 'San Pedro Garza García', 'Nuevo León'),
('67157', 'Praderas del Valle', 'San Pedro Garza García', 'Nuevo León'),
('67158', 'Bosques del Valle', 'San Pedro Garza García', 'Nuevo León'),
('67159', 'Colinas del Valle', 'San Pedro Garza García', 'Nuevo León');

-- GARCÍA
INSERT INTO codigos_postales (codigo, colonia, municipio, estado) VALUES
('66000', 'Centro', 'García', 'Nuevo León'),
('66001', 'Pueblo Nuevo', 'García', 'Nuevo León'),
('66002', 'Privadas de García', 'García', 'Nuevo León'),
('66003', 'Valle de García', 'García', 'Nuevo León'),
('66004', 'Villa de García', 'García', 'Nuevo León'),
('66005', 'Jardines de García', 'García', 'Nuevo León'),
('66006', 'Praderas de García', 'García', 'Nuevo León'),
('66007', 'Rincón de García', 'García', 'Nuevo León'),
('66008', 'Bosques de García', 'García', 'Nuevo León'),
('66009', 'Colinas de García', 'García', 'Nuevo León');

-- Verificar inserción
SELECT COUNT(*) as total_registros FROM codigos_postales;
SELECT municipio, COUNT(*) as total FROM codigos_postales GROUP BY municipio ORDER BY municipio;
