-- ============================================================
-- EXPANSIÓN DE CÓDIGOS POSTALES - NUEVO LEÓN
-- ============================================================
-- Este script expande el catálogo con CPs adicionales
-- basándose en colonias conocidas de cada municipio
-- ============================================================

INSERT INTO codigos_postales (codigo, colonia, municipio, estado) VALUES

-- MONTERREY (completar rango 64000-64999)
('64001', 'Centro Barrio Antiguo', 'Monterrey', 'Nuevo León'),
('64002', 'Centro Metropolitano', 'Monterrey', 'Nuevo León'),
('64003', 'Residencial Centro', 'Monterrey', 'Nuevo León'),
('64070', 'Cumbres 1er Sector Sección A', 'Monterrey', 'Nuevo León'),
('64071', 'Cumbres 1er Sector Sección B', 'Monterrey', 'Nuevo León'),
('64072', 'Cumbres 1er Sector Sección C', 'Monterrey', 'Nuevo León'),
('64073', 'Cumbres 1er Sector Sección D', 'Monterrey', 'Nuevo León'),
('64080', 'Cumbres 2do Sector Sección A', 'Monterrey', 'Nuevo León'),
('64081', 'Cumbres 2do Sector Sección B', 'Monterrey', 'Nuevo León'),
('64082', 'Cumbres 2do Sector Sección C', 'Monterrey', 'Nuevo León'),
('64083', 'Cumbres 2do Sector Sección D', 'Monterrey', 'Nuevo León'),
('64090', 'Cumbres Madeira', 'Monterrey', 'Nuevo León'),
('64095', 'Cumbres San Agustín', 'Monterrey', 'Nuevo León'),
('64101', 'Anáhuac San Patricio', 'Monterrey', 'Nuevo León'),
('64102', 'Anáhuac Chipinque', 'Monterrey', 'Nuevo León'),
('64103', 'Anáhuac Cumbres', 'Monterrey', 'Nuevo León'),
('64170', 'Álamos', 'Monterrey', 'Nuevo León'),
('64230', 'Valle Alto', 'Monterrey', 'Nuevo León'),
('64231', 'Valle del Campestre', 'Monterrey', 'Nuevo León'),
('64232', 'Valle Oriente', 'Monterrey', 'Nuevo León'),
('64233', 'Valle Poniente', 'Monterrey', 'Nuevo León'),
('64270', 'Lomas del Paseo', 'Monterrey', 'Nuevo León'),
('64280', 'Villa Montaña', 'Monterrey', 'Nuevo León'),
('64290', 'Sierra Alta', 'Monterrey', 'Nuevo León'),
('64310', 'Colinas del Huajuco', 'Monterrey', 'Nuevo León'),
('64330', 'Santa Engracia', 'Monterrey', 'Nuevo León'),
('64350', 'Lomas del Roble', 'Monterrey', 'Nuevo León'),
('64370', 'Fuentes del Valle', 'Monterrey', 'Nuevo León'),
('64390', 'Bosques del Valle', 'Monterrey', 'Nuevo León'),
('64430', 'Mirador del Sol', 'Monterrey', 'Nuevo León'),
('64440', 'Lomas del Mirador', 'Monterrey', 'Nuevo León'),
('64470', 'Obrera', 'Monterrey', 'Nuevo León'),
('64490', 'Reforma', 'Monterrey', 'Nuevo León'),
('64510', 'Pío X', 'Monterrey', 'Nuevo León'),
('64530', 'Plutarco Elías Calles', 'Monterrey', 'Nuevo León'),
('64550', 'Residencial Acero', 'Monterrey', 'Nuevo León'),
('64570', 'Deportivo Obispado', 'Monterrey', 'Nuevo León'),
('64590', 'San Francisco', 'Monterrey', 'Nuevo León'),
('64610', 'Leones', 'Monterrey', 'Nuevo León'),
('64630', 'Del Prado', 'Monterrey', 'Nuevo León'),
('64650', 'Revolución', 'Monterrey', 'Nuevo León'),
('64670', 'San Javier', 'Monterrey', 'Nuevo León'),
('64690', 'Cementos', 'Monterrey', 'Nuevo León'),
('64710', 'Juárez', 'Monterrey', 'Nuevo León'),
('64730', 'Emiliano Zapata', 'Monterrey', 'Nuevo León'),
('64750', 'Niño Artillero', 'Monterrey', 'Nuevo León'),
('64770', 'La Alianza', 'Monterrey', 'Nuevo León'),
('64790', 'Benito Juárez', 'Monterrey', 'Nuevo León'),
('64810', 'Villas de San Cristóbal', 'Monterrey', 'Nuevo León'),
('64830', 'Las Puentes 1er Sector', 'Monterrey', 'Nuevo León'),
('64850', 'Las Puentes 2do Sector', 'Monterrey', 'Nuevo León'),
('64870', 'Las Puentes 3er Sector', 'Monterrey', 'Nuevo León'),
('64890', 'Lomas del Canadá', 'Monterrey', 'Nuevo León'),
('64910', 'Canteras', 'Monterrey', 'Nuevo León'),
('64930', 'Caracol', 'Monterrey', 'Nuevo León'),
('64950', 'Villas de San Juan', 'Monterrey', 'Nuevo León'),
('64970', 'Constitución', 'Monterrey', 'Nuevo León'),
('64990', 'Altavista', 'Monterrey', 'Nuevo León'),

-- GUADALUPE (completar rango 67100-67199)
('67101', 'Guadalupe Centro Histórico', 'Guadalupe', 'Nuevo León'),
('67102', 'Guadalupe Viejo', 'Guadalupe', 'Nuevo León'),
('67103', 'Nueva Guadalupe', 'Guadalupe', 'Nuevo León'),
('67111', 'Contry', 'Guadalupe', 'Nuevo León'),
('67112', 'Contry Tesoro', 'Guadalupe', 'Nuevo León'),
('67121', 'Valle de las Palmas', 'Guadalupe', 'Nuevo León'),
('67122', 'Valle Soleado', 'Guadalupe', 'Nuevo León'),
('67131', 'Villa Alegre', 'Guadalupe', 'Nuevo León'),
('67132', 'Villa Jardín', 'Guadalupe', 'Nuevo León'),
('67141', 'Lomas de Guadalupe', 'Guadalupe', 'Nuevo León'),
('67142', 'Lomas del Paseo', 'Guadalupe', 'Nuevo León'),
('67151', 'Jardines del Canadá', 'Guadalupe', 'Nuevo León'),
('67152', 'Jardines del Valle', 'Guadalupe', 'Nuevo León'),
('67161', 'Puente de la Sierra', 'Guadalupe', 'Nuevo León'),
('67162', 'Las Puentes 5to Sector', 'Guadalupe', 'Nuevo León'),
('67171', 'Constitución del 17', 'Guadalupe', 'Nuevo León'),
('67172', 'Valle del Roble', 'Guadalupe', 'Nuevo León'),
('67181', 'El Mirador', 'Guadalupe', 'Nuevo León'),
('67182', 'Campanario', 'Guadalupe', 'Nuevo León'),
('67191', 'Cumbres del Sur', 'Guadalupe', 'Nuevo León'),
('67192', 'Valle del Sol', 'Guadalupe', 'Nuevo León'),

-- SAN NICOLÁS DE LOS GARZA (completar rango 66400-66499)
('66401', 'San Nicolás Centro', 'San Nicolás de los Garza', 'Nuevo León'),
('66402', 'San Nicolás de los Garza Centro', 'San Nicolás de los Garza', 'Nuevo León'),
('66411', 'Colonia Doctores', 'San Nicolás de los Garza', 'Nuevo León'),
('66412', 'Colonia Médica', 'San Nicolás de los Garza', 'Nuevo León'),
('66421', 'Anáhuac Universidad', 'San Nicolás de los Garza', 'Nuevo León'),
('66422', 'Anáhuac la Escondida', 'San Nicolás de los Garza', 'Nuevo León'),
('66431', 'Jardines de Anáhuac Sector 1', 'San Nicolás de los Garza', 'Nuevo León'),
('66432', 'Jardines de Anáhuac Sector 2', 'San Nicolás de los Garza', 'Nuevo León'),
('66441', 'Praderas de San Francisco', 'San Nicolás de los Garza', 'Nuevo León'),
('66442', 'Praderas de Anáhuac', 'San Nicolás de los Garza', 'Nuevo León'),
('66451', 'Cumbres Elite 1er Sector', 'San Nicolás de los Garza', 'Nuevo León'),
('66452', 'Cumbres Elite 2do Sector', 'San Nicolás de los Garza', 'Nuevo León'),
('66461', 'Las Torres 1er Sector', 'San Nicolás de los Garza', 'Nuevo León'),
('66462', 'Las Torres 2do Sector', 'San Nicolás de los Garza', 'Nuevo León'),
('66471', 'Del Maestro', 'San Nicolás de los Garza', 'Nuevo León'),
('66472', 'Del Maestro Norte', 'San Nicolás de los Garza', 'Nuevo León'),
('66481', 'Linda Vista Norte', 'San Nicolás de los Garza', 'Nuevo León'),
('66482', 'Linda Vista Sur', 'San Nicolás de los Garza', 'Nuevo León'),
('66491', 'Mitras Norte 1a Sección', 'San Nicolás de los Garza', 'Nuevo León'),
('66492', 'Mitras Norte 2a Sección', 'San Nicolás de los Garza', 'Nuevo León'),

-- APODACA (completar rango 66600-66699)
('66601', 'Apodaca Centro Norte', 'Apodaca', 'Nuevo León'),
('66602', 'Apodaca Centro Sur', 'Apodaca', 'Nuevo León'),
('66611', 'Las Américas I', 'Apodaca', 'Nuevo León'),
('66612', 'Las Américas II', 'Apodaca', 'Nuevo León'),
('66613', 'Las Américas III', 'Apodaca', 'Nuevo León'),
('66621', 'Portal del Norte', 'Apodaca', 'Nuevo León'),
('66622', 'Portal del Sur', 'Apodaca', 'Nuevo León'),
('66631', 'Villas de Apodaca I', 'Apodaca', 'Nuevo León'),
('66632', 'Villas de Apodaca II', 'Apodaca', 'Nuevo León'),
('66641', 'Las Cumbres 1er Sector', 'Apodaca', 'Nuevo León'),
('66642', 'Las Cumbres 2do Sector', 'Apodaca', 'Nuevo León'),
('66651', 'Real de Palmas I', 'Apodaca', 'Nuevo León'),
('66652', 'Real de Palmas II', 'Apodaca', 'Nuevo León'),
('66661', 'Hacienda Los Morales Sector 1', 'Apodaca', 'Nuevo León'),
('66662', 'Hacienda Los Morales Sector 2', 'Apodaca', 'Nuevo León'),
('66671', 'Los Alisos Norte', 'Apodaca', 'Nuevo León'),
('66672', 'Los Alisos Sur', 'Apodaca', 'Nuevo León'),
('66681', 'Rinconada Colonial 1a Sección', 'Apodaca', 'Nuevo León'),
('66682', 'Rinconada Colonial 2a Sección', 'Apodaca', 'Nuevo León'),
('66691', 'Privadas de Apodaca Oriente', 'Apodaca', 'Nuevo León'),
('66692', 'Privadas de Apodaca Poniente', 'Apodaca', 'Nuevo León'),

-- GENERAL ESCOBEDO
('66051', 'Escobedo Centro', 'General Escobedo', 'Nuevo León'),
('66052', 'Centro Norte', 'General Escobedo', 'Nuevo León'),
('66061', 'Arboleda Norte', 'General Escobedo', 'Nuevo León'),
('66062', 'Arboleda Sur', 'General Escobedo', 'Nuevo León'),
('66071', 'Las Quintas Sector 1', 'General Escobedo', 'Nuevo León'),
('66072', 'Las Quintas Sector 2', 'General Escobedo', 'Nuevo León'),
('66081', 'Privadas de Escobedo Norte', 'General Escobedo', 'Nuevo León'),
('66082', 'Privadas de Escobedo Sur', 'General Escobedo', 'Nuevo León'),
('66091', 'Los Pinos 1a Sección', 'General Escobedo', 'Nuevo León'),
('66092', 'Los Pinos 2a Sección', 'General Escobedo', 'Nuevo León'),

-- SANTA CATARINA
('66351', 'Santa Catarina Centro', 'Santa Catarina', 'Nuevo León'),
('66352', 'Centro Poniente', 'Santa Catarina', 'Nuevo León'),
('66361', 'Jardines de Santa Catarina 1a Sección', 'Santa Catarina', 'Nuevo León'),
('66362', 'Jardines de Santa Catarina 2a Sección', 'Santa Catarina', 'Nuevo León'),
('66371', 'Las Quintas Norte', 'Santa Catarina', 'Nuevo León'),
('66372', 'Las Quintas Sur', 'Santa Catarina', 'Nuevo León'),
('66381', 'Colinas I', 'Santa Catarina', 'Nuevo León'),
('66382', 'Colinas II', 'Santa Catarina', 'Nuevo León'),
('66391', 'Balcones 1er Sector', 'Santa Catarina', 'Nuevo León'),
('66392', 'Balcones 2do Sector', 'Santa Catarina', 'Nuevo León'),

-- SAN PEDRO GARZA GARCÍA
('66201', 'San Pedro Centro', 'San Pedro Garza García', 'Nuevo León'),
('66202', 'Centro Norte', 'San Pedro Garza García', 'Nuevo León'),
('66211', 'Del Valle Oriente', 'San Pedro Garza García', 'Nuevo León'),
('66212', 'Del Valle Poniente', 'San Pedro Garza García', 'Nuevo León'),
('66221', 'Fuentes del Valle Norte', 'San Pedro Garza García', 'Nuevo León'),
('66222', 'Fuentes del Valle Sur', 'San Pedro Garza García', 'Nuevo León'),
('66231', 'Las Cumbres 1er Sector', 'San Pedro Garza García', 'Nuevo León'),
('66232', 'Las Cumbres 2do Sector', 'San Pedro Garza García', 'Nuevo León'),
('66241', 'Lomas de San Francisco Norte', 'San Pedro Garza García', 'Nuevo León'),
('66242', 'Lomas de San Francisco Sur', 'San Pedro Garza García', 'Nuevo León'),
('66251', 'Residencial San Agustín 1', 'San Pedro Garza García', 'Nuevo León'),
('66252', 'Residencial San Agustín 2', 'San Pedro Garza García', 'Nuevo León'),
('66261', 'Carrizalejo Norte', 'San Pedro Garza García', 'Nuevo León'),
('66262', 'Carrizalejo Sur', 'San Pedro Garza García', 'Nuevo León'),
('66271', 'La Joya', 'San Pedro Garza García', 'Nuevo León'),
('66272', 'La Joya Privada', 'San Pedro Garza García', 'Nuevo León')

ON CONFLICT DO NOTHING;

-- Verificación
SELECT COUNT(*) as total_registros FROM codigos_postales;

SELECT municipio, COUNT(*) as colonias
FROM codigos_postales
GROUP BY municipio
ORDER BY colonias DESC;
